version: '3'
services:
  app:
    build:
      context: .
    restart: always
    container_name: manage_sonoff_app
    environment:
      - DEVICES_FILE=devices.json
      - GIN_MODE=release
    ports:
      - 8088:8080
    tty: true