version: '3'
services:
  app:
    build:
      context: .
    restart: always
    container_name: manage_sonoff_app
    environment:
      DEVICES_FILE: config/devices.json
      GIN_MODE: release
      MQTT_SENDER_HOST: mqttsender:8075
    ports:
      - 8088:8080
    tty: true